### ISSUE TITLE
Querying Geo locations

### ISSUE THREAD

**Issue by amitjindal** [medcl/ElasticSearch.Net#2]
Hi, I was looking for a .net api to elastic search and found this project. I have a question though. I need to use geo location search for distance. How can I do that with this library?

Thanks for this library!

Jack

**Comment by medcl** [comment]
this api is not available right now,but it is easy to hack on,i will add it soon, :)

**Comment by amitjindal** [comment]
Thanks for replying.
Could you please let me know when you will be able to do that? I will wait as I cannot evaluate this without geo_distance. I only need geo_distance for now.
Also if you could guide me on how to add similar things, I could possibly try and do that myself.

**Comment by medcl** [comment]
done,check it out.fdf6213053b33216cc34833b392451266768b17c

a example:
var geoDistanceFilter = new GeoDistanceFilter("pin.location", "40,-70", "200km");
var result = client.Search(index, "type", new FilteredQuery(new MatchAllQuery(), geoDistanceFilter));
